### ISSUE TITLE
variable total_season_* not found

### ISSUE THREAD

**Issue by emawbgit** [jdavidm/weather_command#2]
Hello, I want to analyze some chirps data using this command. I have arranged the daily chirps data in the wide format/naming required from the command. I have written the syntax as I understood it from the pdf readme. Though I now get this error message that I cannot debug even if I set trace on. This is the dataset:
![image](https://github.com/jdavidm/weather_command/assets/65594313/f7df04fa-ac79-4932-8e57-b15a6dcd2cd1)

This is the code and error I get:
![image](https://github.com/jdavidm/weather_command/assets/65594313/e0431c8e-da70-4941-ade7-7be753aa9b52)

Looking forward to your feedback. Thanks,
Emanuele (World Bank, DECPM)

**Comment by emawbgit** [comment]
It may be related to the j index
![image](https://github.com/jdavidm/weather_command/assets/65594313/425625db-7140-40fa-b74e-c1db6f631cf9)

**Comment by jdavidm** [comment]
@emawbgit thanks for finding this bug. The issue was that in the code I had set the start year too late (1983) for the data you were using (which starts in 1981). I've now updated the window in which it looks for the year. I ran updated program on the data you shared and it worked perfectly. Please fetch the updated repo with the new commits from today and try it again. Let me know if it doesn't work.

**Comment by emawbgit** [comment]
Hello Jeff, unfortunately I still get the same error message after reinstalling the command (i.e. placed the updated .ado in the ado/w folder

**Comment by jdavidm** [comment]
I'm at a bit of a lose. I've been able to run the command on three different machines, all successfully. Can you verify again that you are using the correct syntax: weather pic_, rain_data ini_month(1) fin_month(3) day_month(15) keep(arable_barcode)?

**Comment by emawbgit** [comment]
Ok now it works! Thank you so much Jeff
________________________________
